[package]
name = "tabpane"
version = "0.1.0"

[page]
title = "New Tab"
lang = "en"

[build]
target = "js"
out = "build"

[[bin]]
path = "src/home.maca"

[dependencies]
daisyui = "npm:daisyui@^4"
iconify-icon = "npm:iconify-icon"

[format]
indent_style = "space"
indent_size = 2
